sudo: false
language: python
python:
- '3.4'
before_install:
<<<<<<< HEAD
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
script:
- build.sh
=======
  - chmod +x build.sh
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
script:
  - build.sh
>>>>>>> initial commit
